import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import HeroCard from "../components/HeroCard";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>TDP Documentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="mx-auto mt-12 w-2/3">
        <main className="grid w-full gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          <HeroCard
            cardTitle="Construction"
            location="/docs/construction"
            image="/construction.webp"
            imageAltText="Construction"
          />
          <HeroCard
            cardTitle="Transportation"
            location="/docs/transportation"
            image="/transportation.webp"
            imageAltText="Transportation"
          />
          <HeroCard
            cardTitle="Agriculture"
            location="/docs/agriculture"
            image="/agriculture.webp"
            imageAltText="Agriculture"
          />
        </main>
      </div>
    </div>
  );
};

export default Home;
